// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FB
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct FBMetadataNode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static FBMetadataNode GetRootAsFBMetadataNode(ByteBuffer _bb) { return GetRootAsFBMetadataNode(_bb, new FBMetadataNode()); }
  public static FBMetadataNode GetRootAsFBMetadataNode(ByteBuffer _bb, FBMetadataNode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBMetadataNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong UniqueID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Metadata { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMetadataBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMetadataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMetadataArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FB.FBMetadataNode> CreateFBMetadataNode(FlatBufferBuilder builder,
      ulong UniqueID = 0,
      StringOffset MetadataOffset = default(StringOffset)) {
    builder.StartTable(2);
    FBMetadataNode.AddUniqueID(builder, UniqueID);
    FBMetadataNode.AddMetadata(builder, MetadataOffset);
    return FBMetadataNode.EndFBMetadataNode(builder);
  }

  public static void StartFBMetadataNode(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUniqueID(FlatBufferBuilder builder, ulong UniqueID) { builder.AddUlong(0, UniqueID, 0); }
  public static void AddMetadata(FlatBufferBuilder builder, StringOffset MetadataOffset) { builder.AddOffset(1, MetadataOffset.Value, 0); }
  public static Offset<FB.FBMetadataNode> EndFBMetadataNode(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FB.FBMetadataNode>(o);
  }
};


}
