# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBColor(object):
    __slots__ = ['_tab']

    # FBColor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBColor
    def R(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # FBColor
    def G(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # FBColor
    def B(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # FBColor
    def NoColor(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(3))

def CreateFBColor(builder, R, G, B, NoColor):
    builder.Prep(1, 4)
    builder.PrependBool(NoColor)
    builder.PrependUint8(B)
    builder.PrependUint8(G)
    builder.PrependUint8(R)
    return builder.Offset()
