# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBMetadataNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBMetadataNode(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBMetadataNode()
        x.Init(buf, n + offset)
        return x

    # FBMetadataNode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBMetadataNode
    def UniqueID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FBMetadataNode
    def Metadata(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FBMetadataNodeStart(builder): builder.StartObject(2)
def FBMetadataNodeAddUniqueID(builder, UniqueID): builder.PrependUint64Slot(0, UniqueID, 0)
def FBMetadataNodeAddMetadata(builder, Metadata): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Metadata), 0)
def FBMetadataNodeEnd(builder): return builder.EndObject()
