# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FBVector3D(object):
    __slots__ = ['_tab']

    # FBVector3D
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBVector3D
    def X(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # FBVector3D
    def Y(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # FBVector3D
    def Z(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateFBVector3D(builder, X, Y, Z):
    builder.Prep(4, 12)
    builder.PrependFloat32(Z)
    builder.PrependFloat32(Y)
    builder.PrependFloat32(X)
    return builder.Offset()
